# Generated by Django 4.1.7 on 2023-05-15 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_carrera_remove_personas_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRUD.carrera'),
        ),
    ]
